// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDb8euYMZTypAnF4817UxNrp-9ToIoItw',
    appId: '1:1034677541127:web:d7d9be9236fa5359964da2',
    messagingSenderId: '1034677541127',
    projectId: 'testebroker-8cc87',
    authDomain: 'testebroker-8cc87.firebaseapp.com',
    storageBucket: 'testebroker-8cc87.appspot.com',
    measurementId: 'G-JXLFK08RV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumPBHwhVA0-Degks3CqwOXCr2nz7S9vo',
    appId: '1:1034677541127:android:36f5b6431239c8d9964da2',
    messagingSenderId: '1034677541127',
    projectId: 'testebroker-8cc87',
    storageBucket: 'testebroker-8cc87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdMCc8EMzhhSP5DzP3WE40xyq2flCBokE',
    appId: '1:1034677541127:ios:cf2717dcd1910913964da2',
    messagingSenderId: '1034677541127',
    projectId: 'testebroker-8cc87',
    storageBucket: 'testebroker-8cc87.appspot.com',
    iosBundleId: 'com.ebroker.wrteam',
  );
}
